id: I1BE6B7B6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T22:29:51+00:00'
last_modified: '2022-06-07T21:24:18.025582+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25569
  title: ཁ་སང་གི་ཚོ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '6440':
      image_group_id: I1KG25571
      title: ''
      total_pages: 274
      order: 1
      base_file: 6440.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
