id: P004249
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG25569
  title: ཁ་སང་གི་ཚོ་བ།
  author: ''
  volumes:
    cf3527e4a9104698b603d62437062ba0:
      image_group_id: I1KG25571
      title: ''
      volume_number: 1
      total_pages: 274
      base_file: v001.txt
